---
title: "sim"
author: "Alex Carriero"
output: 
   bookdown::html_document2:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: false
    theme: paper
---

<style type="text/css">
  
body{ /* Normal  */
  font-size: 12px;
  }
td {  /* Table  */
  font-size: 12px;
}
h1.title {
  font-size: 18px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 18px;
}
h2 { /* Header 2 */
  font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 18px;
}
code.r{ /* Code block */
  font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
  font-size: 14px;
}
</style>

---

# Set up 
```{r, warning = F, message = F, echo = F}
# libraries 

# general
library(tidyverse)
library(devtools)
library(MASS)

# pre-processing corrections
library(ROSE)
library(smotefamily)

# models 
library(glmnet)
library(e1071)
library(randomForest)
library(xgboost)
library(ebmc)

# simulation features 
library(pROC)
library(SimDesign)
library(simsalapar)
```

```{r, echo = F}
# how to install IRIC package from github
```

```{r}
# simulation scenarios 

set <- readRDS("set.RData")
```
 
```{r}
# functions

source("functions.R")
```

```{r}
# simulation function 

simulation <- function(sc, iter){
  
  start    <- Sys.time()
  scenario <- set[[sc]]

  iter  <- iter
  auc   <- matrix(data = 0, nrow = iter, ncol = 5)
  bri   <- matrix(data = 0, nrow = iter, ncol = 5)
  int   <- matrix(data = 0, nrow = iter, ncol = 5)
  slp   <- matrix(data = 0, nrow = iter, ncol = 5)

  plot <- ggplot() + 
          geom_abline(slope = 1, intercept = 0, size = 1) +
          scale_color_brewer(palette = "Set2") +
          xlab("Estimated Probability") +
          ylab("Observed Proportion") +
          ggtitle("Flexible Calibration Curves") + 
          theme_minimal() 

  for (i in 1:iter){    
      df       <- generate_data(scenario)
      test     <- generate_data(scenario, test = TRUE)
    
      pp       <- pred_probs(df, test)
      
      ppl      <- pp %>%
                  pivot_longer(-class, names_to = "variable")
    
      auc[i,]  <- quiet(get_auc(pp))
      bri[i,]  <- get_brier_score(pp)
      int[i,]  <- get_int(pp)
      slp[i,]  <- get_slp(pp)
    
      plot     <- plot + 
                  geom_smooth(data = ppl, 
                              aes(x = value, y = as.numeric(class) -1, color = variable), 
                              method = stats::loess, 
                              formula = y ~ x,
                              se = F, 
                              size = 0.1) +
                  facet_wrap(~variable)
  }
  
  
  ggsave(paste0("plot_",sc,".pdf"), plot)  # save plot
  stats <- get_stats(auc, bri, int, slp)   # save statistics
  
  end <- Sys.time()
  dif <- difftime(end, start, units = "mins")
  
  out   <- list("runtime" = dif, "stats" = stats) 
  return(out)
}
```


# Results 

```{r, warning = F}
### 8 Predictors, EV = 0.5, N = 0.5N
sim_1 <- quiet(simulation(sc = 1, iter = 100))   # run simulation 
saveRDS(sim_1, file = "sim_1.rds")               # save results


### 8 Predictors, EV = 0.2,  N = 0.5N
sim_2 <- quiet(simulation(sc = 2, iter = 100))   # run simulation 
saveRDS(sim_2, file = "sim_2.rds")               # save results


### 8 Predictors, EV = 0.02, N = 0.5N
sim_3 <- quiet(simulation(sc = 3, iter = 100))   # run simulation 
saveRDS(sim_3, file = "sim_3.rds")               # save results


### 8 Predictors, EV = 0.5,  N = N
sim_4 <- quiet(simulation(sc = 4, iter = 100))   # run simulation 
saveRDS(sim_4, file = "sim_4.rds")               # save results


### 8 Predictors, EV = 0.2,  N = N
sim_5 <- quiet(simulation(sc = 5, iter = 100))   # run simulation 
saveRDS(sim_5, file = "sim_5.rds")               # save results


### 8 Predictors, EV = 0.02, N = N
sim_6 <- quiet(simulation(sc = 6, iter = 100))   # run simulation 
saveRDS(sim_6, file = "sim_6.rds")               # save results


### 8 Predictors, EV = 0.5, N = 2N
sim_7 <- quiet(simulation(sc = 7, iter = 100))   # run simulation 
saveRDS(sim_7, file = "sim_7.rds")               # save results


### 8 Predictors, EV = 0.2, N = 2N
sim_8 <- quiet(simulation(sc = 8, iter = 100))   # run simulation 
saveRDS(sim_8, file = "sim_8.rds")               # save results

### 8 Predictors, EV = 0.02, N = 2N
sim_9 <- quiet(simulation(sc = 9, iter = 100))   # run simulation 
saveRDS(sim_9, file = "sim_9.rds")               # save results
```



# One iteration
```{r}
scenario <- set[[1]]
```

```{r}
df   <- generate_data(scenario)
test <- generate_data(scenario, test = TRUE)
pp   <- pred_probs(df, test)

ppl  <- pp %>%
        pivot_longer(-class, names_to = "variable")
```

```{r, echo = F}
plot <- ggplot() + 
        geom_abline(slope = 1, intercept = 0, size = 1) +
        scale_color_brewer(palette = "Set2") +
        xlab("Estimated Probability") +
        ylab("Observed Proportion") +
        ggtitle("Flexible Calibration Curves") + 
        theme_minimal() 

plot + geom_smooth(data = ppl, aes(x = value, y = as.numeric(class) -1, color = variable), 
                   method = stats::loess, 
                   formula = y~x,
                   se = F, 
                   size = 0.3)+
        facet_wrap(~variable)
```
```{r}
quiet(get_auc(pp))
```
```{r}
get_brier_score(pp)
```
```{r}
probs <- pp$lrg
outcome <- pp$class
mod <- glm(outcome ~ 1, offset = log(probs/(1-probs)), family = "binomial")
mod <- glm(outcome ~ log(probs/(1-probs)), family = "binomial")
summary(mod)
coef(mod)[1]
```

```{r}
for(i in 1:1000){
df   <- generate_data(scenario)
test <- generate_data(scenario, test = TRUE)
pp   <- pred_probs(df, test)
get_int(pp)
get_slp(pp)
}


table(pp$class)
get_int(pp)
get_slp(pp)

outcome <- pp$class
probs <- pp$rnf
mod <- glm(outcome ~ 1, offset = log(probs/(1-probs)), family = "binomial")
mod <- glm(outcome ~ log(probs/(1-probs)), family = "binomial")

sum(is.na(probs))
min(probs)
hist(log(probs/(1-probs)))

log(0/(1-0))
```
```{r}
calibration_intercept <- function(probs, outcome){
  
  if(sum(probs == 1) != 0){
    probs[probs == 1] <- 0.999
  }
  if(sum(probs == 0) != 0){
    probs[probs == 0] <- 0.001
  }
  mod <- glm(outcome ~ 1, offset = log(probs/(1-probs)), family = "binomial")
  int <- coef(mod)[1]
  return(int)
}

calibration_slope <- function(probs, outcome){
  
  if(sum(probs == 1) != 0){
    probs[probs == 1] <- 0.999
  }
  if(sum(probs == 0) != 0){
    probs[probs == 0] <- 0.001
  }
  mod <- glm(outcome ~ log(probs/(1-probs)), family = "binomial")
  slp <- coef(mod)[2]
  return(slp)
}
```

```{r}
calibration <- function(probs,outcome){
  brier_score <- brier(probs, outcome)
  
  if (sum(probs == 1) != 0){
    probs[probs == 1] <- 1 - ((1-max(probs[probs != 1]))/2)
  } 
  
  if (sum(probs == 0) != 0) {
    probs[probs == 0] <- min(probs[probs != 0]) /2 
  }
  
  slope_model <- glm(outcome ~ log(probs/(1-probs)), family = "binomial")
  slope <- coef(slope_model)[2]
  attributes(slope) <- NULL
  intercept_model <- glm(outcome ~ 1, 
                         offset = log(probs/(1-probs)), 
                         family = "binomial")
  intercept <- coef(intercept_model)
  attributes(intercept) <- NULL
  cal_results <- c(intercept, slope, brier_score)
  
  return(cal_results)
}
```




