---
title: "scraps"
author: "Alex Carriero"
date: '2022-10-04'
output: html_document
---

- class imbalance is thought to be a problem that needs solving 

- Three broad categories of class imbalance corrections emerge from the literature: pre-processing techniques, cost-sensitive learning and ensemble learning.

-  In other words, once a risk threshold is chosen, the continuous risk predictions generated by the model (ranging from 0-1) are transformed into binary predictions such that patients with a risk prediction greater than the threshold are predicted belong to the positive class and those below it to the negative class. 

- In medicine, data sets are often heavily imbalanced, due to the (thankfully) rare nature of many diseases, but it is unacceptable to apply corrections for class imbalance without consideration for their effect on model calibration in a medical context.

- Patients who experience the event are collectively referred to as the positive class, while those who do not, are referred to as the negative class. 

- dicsrimintion : it is quantified by area under the receiver operating curve (AUROC), also referred to as the concordance statistic

- where  is the quality of the risk predictions determine how clinically useful a model is. This is because risk predictions are used directly by clinicians to council patients and inform treatment decisions, thus, if prediction models are not well calibrated, in a medical context, the consequences may be catastrophic.   For instance, if patient's true risk of death is 20%, yet the model predicts their risk to be 80%, this will prediction may do more harm than good to the patient.

- However, a model can have high accuracy and discrimination while the reliability of the risk predictions produced by the model (calibration) is poor [@achilles].  

- This leads us to the dilemma which motivates our research question:  class imbalance is thought to be a problem that needs solving.  Yet, while an abundance of class imbalance correction methods exist [@summary_lp, @summary_m, @summary_b, @summary_h], comparisons of these various class imbalance corrections typically fail to assess model calibration.  Additionally, a recent study demonstrated that when predictive models are developed using logistic regression, applying particular class imbalance corrections dramatically deteriorated the calibration of the model [@ruben]. In medicine, data sets are often heavily imbalanced, due to the (thankfully) rare nature of many diseases, but it is unacceptable to apply corrections for class imbalance without consideration for their effect on model calibration in a medical context. 